# This is the Compose file for command-line services.
# Anything that doesn't need to be run as part of the main `docker-compose up'
# command should reside in here and be invoked by a helper script.
version: "3.7"
services:
  wp:
    build: ./services/wp-cli
    volumes:
      - ./services/wordpress:/var/www/html:cached
      - type: volume
        source: fs-data
        target: /var/www/html/public/wp-content/uploads
  wp-bulk-command:
    image: timnolte/wp-bulk-command:latest
    volumes:
      - ./services/wordpress:/var/www/html:cached
      - ~/.ssh:/root/.ssh:ro
  composer:
    image: forumone/composer:1.9
    volumes:
      - ./services/wordpress:/app:cached
volumes:
  {}
