# This is the Compose file for command-line services.
# Anything that doesn't need to be run as part of the main `docker-compose up'
# command should reside in here and be invoked by a helper script.
version: "3.7"

services:
  wp-bulk-command:
    image: timnolte/wp-bulk-command:latest
    volumes:
      - ${PWD}:/var/www/html:cached
      - ~/.ssh:/root/.ssh:ro

volumes:
  {}
